import { Random } from 'meteor/random';
import { CariKartlar, Bakiye, Etiketler } from '/imports/api/model';
import { CARI_KARTLAR, ETIKETLER, } from '/imports/environment/enums';
import { CKID } from './shared/id';

export default function createCariKartFixture() {

  [
    {
      _id: ACENTA = Random.id(),
      tip: ETIKETLER.CARI_KART.value,
      isim: 'Acenta',
    },
    {
      _id: KAMU = Random.id(),
      tip: ETIKETLER.CARI_KART.value,
      isim: 'Kamu',
    },
    {
      _id: BANKA = Random.id(),
      tip: ETIKETLER.CARI_KART.value,
      isim: 'Banka',
    },
    {
      _id: PERSONEL = Random.id(),
      tip: ETIKETLER.CARI_KART.value,
      isim: 'Personel',
    },
    {
      _id: TEDARIKCI = Random.id(),
      tip: ETIKETLER.CARI_KART.value,
      isim: 'Tedarikçi',
    },
    {
      _id: OTEL = Random.id(),
      tip: ETIKETLER.CARI_KART.value,
      isim: 'Otel',
    },
  ].forEach(etiket => {
    Etiketler.insert(etiket);
  });

  [
    {
      _id: VD = Random.id(),
      etiketler: [KAMU],
      tip: CARI_KARTLAR.KURUM.value,
      unvan: 'ANTALYA VERGİ DAİRESİ BAŞKANLIĞI 007107 KAŞ MAL MÜDÜRLÜĞÜ',
      kisaIsim: 'Vergi Dairesi',
    },
    {
      _id: YKB = Random.id(),
      etiketler: [BANKA],
      tip: CARI_KARTLAR.KURUM.value,
      unvan: 'Yapı Kredi Bankası',
      kisaIsim: 'YKB',
    },
    {
      _id: YKB_KK_1 = Random.id(),
      etiketler: [BANKA],
      tip: CARI_KARTLAR.KURUM.value,
      unvan: 'Yapı Kredi Bankası Kredi Kartı Murat Draman',
      kisaIsim: 'YKB KK Murat Draman',
    },
    {
      _id: YKB_KK_2 = Random.id(),
      etiketler: [BANKA],
      tip: CARI_KARTLAR.KURUM.value,
      unvan: 'Yapı Kredi Bankası Kredi Kartı Tolga Yücel',
      kisaIsim: 'YKB KK Tolga Yücel',
    },
    { _id: PR1 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'ÇAĞATAY ARICAN', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'cagatay@dragoman-turkey.com', telefon: '5556258167', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR040006701000000043782431' },
    { _id: PR2 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'EROL BOZDAĞ', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: '5362490468', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR200006701000000092183494' },
    { _id: PR3 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'GÜVENÇ DUMAN', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'guvencduman@hotmail.com', telefon: '5363176267', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR130006701000000072229847' },
    { _id: PR4 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'HALİL İBRAHİM YILMAZ', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: '5537441731', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: PR5 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'HATİCE BOZDAĞ', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: '5378580545', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: PR6 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'KADRİYE ELİF TERZİOĞLU', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'elif@dragoman-turkey.com', telefon: '5332853570', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR850006701000000092441023' },
    { _id: PR7 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'KEVSER MERMERTAŞ', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'kevser@dragoman-turkey.com', telefon: '5323974731', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR700006701000000001437348' },
    { _id: PR8 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'MURAT DRAMAN', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'murat@dragoman-turkey.com', telefon: '5322321668', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: PR9 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'OKAN HALAÇOĞLU', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'ohalacoglu@gmail.com', telefon: '5380158219', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR740006701000000085177376' },
    { _id: PR10 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'ÖMER AKMAN', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'oakmankas@gmail.com', telefon: '5337479122', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR720006701000000072230822' },
    { _id: PR11 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'OZAN ATABİLEN', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'ozan@dragoman-turkey.com', telefon: '5359218484', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR890006200107200006697914' },
    { _id: PR12 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'TOLGA OSMAN YÜCEL', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'tolga@dragoman-turkey.com', telefon: '5423873155', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR520006400000112230039355' },
    { _id: PR13 = Random.id(), tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'TUBA ÖZ', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'tuba@dragoman-turkey.com', telefon: '5323972389', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR610006701000000082326198' },
    { _id: CKID.CK1, tip: 'kurum', etiketler: undefined, unvan: 'KAŞ EXPLORERS ', kisaIsim: 'ALTUĞ ve BELMA TOSUN', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: '5364245215', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: CKID.CK2, tip: 'kurum', etiketler: undefined, unvan: 'ÇÖLLÜ DENİZ YAT.İTH.SAN.TİC.LTD.ŞTİ', kisaIsim: 'Çöllü', adres: 'YEŞİLOVA MAH.ASPENDOS BULV NO 140 07100 MURATPAŞA ', sehir: 'Antalya', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'ANTALYA KURUMLAR', vergiNumarasi: '2630316806', iban: undefined },
    { _id: CKID.CK3, tip: 'kurum', etiketler: undefined, unvan: 'PROMAR GÖRÜNTÜLEME VE KORUMA MALZEMELERİ TİC.LTD.ŞTİ', kisaIsim: 'ATEŞ EVİRGEN', adres: 'EĞİTİM MAH ADIM SOK NO 4 ATAOL PLAZA K.2 DR.19 34722 KADIKÖY', sehir: 'İstanbul', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'KADIKÖY', vergiNumarasi: '7330380875', iban: undefined },
    { _id: CKID.CK4, tip: 'kurum', etiketler: undefined, unvan: 'ATLAS DALIŞ MERKEZİ', kisaIsim: 'MERTCAN KIRGIZ', adres: 'Yat Limanı', sehir: 'Antalya', webSitesi: undefined, email: undefined, telefon: '5369557339', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: CKID.CK5, tip: 'kurum', etiketler: undefined, unvan: 'PADEM KİTAP TEKSTİL ÇANTA DALIŞ MALZ.PAZARLAMA SATIŞ', kisaIsim: 'EMRE GÜLCAN', adres: 'ÖRNEKKÖY MAH YENİ GİRNE CAD 7445 SOK N.6 ZEMİN KAT KARŞIYAKA', sehir: 'İzmir', webSitesi: 'http://www.pademtr.com', email: undefined, telefon: '2323650604', vergiDairesi: 'YAMANLAR', vergiNumarasi: '21739150132', iban: undefined },
    { _id: CKID.CK6, tip: 'kurum', etiketler: [ACENTA], unvan: 'Le Congé Travel – Mavi Kaş Turizm', kisaIsim: 'MAVİ KAŞ TURİZM', adres: 'Uzunçarşı Sokak No: 5 07580 Kaş', sehir: 'Antalya', webSitesi: 'http://mavikas.com', email: 'info@mavikas.com', telefon: '2428364512', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: CKID.CK7, tip: 'kurum', etiketler: [TEDARIKCI], unvan: 'PANDORA YAYI VE KİTAP HİZMETLERİ AŞ', kisaIsim: 'PANDORA', adres: 'PERİHAN SOK EMEK İŞ HANI NO 68/2 ŞİŞLİ', sehir: 'İstanbul', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'ŞİŞLİ', vergiNumarasi: '7210430431', iban: undefined },
    { _id: CKID.CK8, tip: 'sahis', etiketler: [TEDARIKCI], unvan: 'NERMO DESIGN', kisaIsim: 'IŞIL AKTAŞ ÖZCAN', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'nermodesign@gmail.com', telefon: '5443425824', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: CKID.CK9, tip: 'kurum', etiketler: undefined, unvan: 'URANUS FOTOGRAFÇILIK YAYINCILIK REKLAMCILIK SAN.VE TİC.LTD.ŞTİ', kisaIsim: 'URANÜS', adres: 'ANKARA CAD.CAĞALOĞLU YOKUŞU EVREN HAN NO.23 KAT 2/40', sehir: 'İstanbul', webSitesi: undefined, email: undefined, telefon: '2125280158', vergiDairesi: 'HOCAPAŞA', vergiNumarasi: '8930271741', iban: 'TR110006200070500006298894' },
    { _id: CKID.CK10, tip: 'kurum', etiketler: [TEDARIKCI], unvan: 'CRIANZ POTTERY', kisaIsim: 'BUKET BALIK', adres: undefined, sehir: undefined, webSitesi: 'http://crianz.com', email: 'info@crianz.com', telefon: '5059933502', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: CKID.CK11, tip: 'sahis', etiketler: [TEDARIKCI], unvan: undefined, kisaIsim: 'ŞİMA KAVACIK', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: CKID.CK12, tip: 'sahis', etiketler: [TEDARIKCI], unvan: 'SEATHINKS TASARIM HİZMETLERİ', kisaIsim: 'GÖKÇE DURUSOY', adres: 'Orhan Veli Kanık Cad. No: 64 D: 14 Kavacık Beykoz', sehir: 'İstanbul', webSitesi: 'http://www.seathinks.com', email: 'sea@seathinks.com', telefon: '5324741989', vergiDairesi: 'BEYKOZ', vergiNumarasi: '23990088650', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'TTC Turizm ve Otelcilik Dış Ticaret Ltd. Şti.', kisaIsim: 'MYSIA TRAVEL', adres: 'Alemdar Mah. Divanyolu Cad. Oğul Han No:62 Kat:4 Sultanhamet', sehir: 'İstanbul', webSitesi: 'http://www.turkeytravelcenter.com', email: 'info@turkeytravelcenter.com', telefon: '2124589940', vergiDairesi: 'Hocapaşa V.D.', vergiNumarasi: '8590531659', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'SRM TURİZM İÇ VE DIŞ TİC AŞ ', kisaIsim: 'SRM TRAVEL', adres: 'Bagdat Caddesi No:179 D:5 Ciftehavuzlar  Kadikoy 34724', sehir: 'İstanbul', webSitesi: 'http://www.srmtravel.com', email: 'tour@srmtravel.com', telefon: '2163867521', vergiDairesi: 'GÖZTEPE', vergiNumarasi: '7810500946', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'Burc İktisadi İşletmesi - BOĞAZİÇİ ÜNİVERSİTESİ MEZUNLAR DERNEĞİ ', kisaIsim: 'BÜMED', adres: 'BÜMED Güney Kampüs 6 Nolu Lojman 34342 Bebek', sehir: 'İstanbul', webSitesi: 'http://www.bumed.org.tr', email: 'elifbakirlioglu@bumed.org.tr', telefon: '2123595800', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR340006200129500006600207' },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'Bougainville Turizm Seyehat Ltd. Şti.', kisaIsim: 'BEGONVİL TRAVEL', adres: 'ÇUKURBAĞLI Cad. No. 10, Ka 07580', sehir: 'Antalya', webSitesi: 'http://www.bougainville-turkiye.com', email: 'sales@bougainville-turkey.com', telefon: undefined, vergiDairesi: 'KAŞ MAL MÜDÜRLÜĞÜ', vergiNumarasi: '1810024959', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'KAHRAMANLAR TURİZM VE YATÇILIK A.Ş.', kisaIsim: 'KAHRAMANLAR MEIS FERRY', adres: 'Cumhuriyet Meydanı No:19/A Kaş', sehir: 'Antalya', webSitesi: 'http://www.meisferrylines.com', email: 'info@meisferrylines.com', telefon: '2428361800', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'UNIVERSAL TURIZM VE TİCARET AŞ', kisaIsim: 'UNİVERSAL TRAVEL', adres: 'Ferah Sokak No:29 Tesvikiye 34365', sehir: 'İstanbul', webSitesi: 'http://www.universaltravel-tr.com', email: 'universal@universaltravel-tr.com', telefon: '2122259232', vergiDairesi: 'MECİDİYEKÖY ', vergiNumarasi: '9130028462', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'KARAVAN TURİZM SEY.VE NAK. AŞ', kisaIsim: 'KARAVAN TRAVEL', adres: 'HALASKARGAZİ CAD GAZİ ETHEM PAŞA SİTESİ NO 112 K.7 OSMANBEY', sehir: 'İstanbul', webSitesi: 'http://karavantravel.com', email: 'umit.yasar@karavantravel.com', telefon: '2122475044', vergiDairesi: 'ÇAKABEY', vergiNumarasi: '5230000472', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'PROPERTRAVEL SEYAHAT DANIŞMANLIĞI T', kisaIsim: 'TRAVEL ATELIER', adres: 'Istiklal Caddesi Proper House No:54, 50400 Urgup', sehir: 'Nevşehir', webSitesi: 'http://travelatelier.com', email: 'info@travelatelier.com', telefon: '3843416520', vergiDairesi: 'ÜRGÜPMAL MÜDÜRLÜĞÜ', vergiNumarasi: '7330284688', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'İzler Turizm San. Tic. Ltd. Şti.', kisaIsim: 'TERRA ANATOLIA', adres: 'Kılınçarslan Mah. 2. Sakarya Sok. Uysal Apt. 2/5 Kaleiçi /Muratpaşa', sehir: 'Antalya', webSitesi: 'http://www.terra-anatolia.com', email: 'info@terra-anatolia.com', telefon: '2422448945', vergiDairesi: 'Kurumlar Vergi Dairesi', vergiNumarasi: '4840559158', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'YERDENİZ SEY.ACENT.TUR.TİC.LTD.ŞTİ ', kisaIsim: 'MIDDLE EARTH', adres: 'ORTACA MAH KARŞI BUÇAK CAD NO 40/1 GÖREME', sehir: 'Nevşehir', webSitesi: 'http://www.middleearthtravel.com', email: 'info@middleearthtravel.com', telefon: '3842712559', vergiDairesi: 'NEVŞEHİR', vergiNumarasi: '9490202292', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: undefined, kisaIsim: 'AMMARE TURZ VE SEY ACENT.LTD ŞTİ', adres: 'OSMANYILMAZ MAH İSTANBUL CAD N.80/D GEBZE', sehir: 'Kocaeli', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'ULUÇINAR', vergiNumarasi: '680823955', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'Simena Turizm A.S.', kisaIsim: 'AMBER TRAVEL', adres: 'Simena Turizm A.S. Halk Konutlari, Yilmaz Apt. 07580 Kas', sehir: 'Antalya', webSitesi: 'http://www.ambertravel.com', email: 'info@ambertravel.com', telefon: '2428361630', vergiDairesi: 'KAŞ', vergiNumarasi: '3880180609', iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: undefined, kisaIsim: 'HIKE & SAIL', adres: undefined, sehir: undefined, webSitesi: 'http://www.hikensail.com', email: 'serkan@hikensail.com', telefon: '2163630838', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { tip: 'kurum', etiketler: [ACENTA], unvan: 'Doruk Turizm Sey. Ve Tic. Ltd. Şti.', kisaIsim: 'SAMİSTAL TRAVEL', adres: 'Yukarı Kayabaşı, Bor Cad., Bilim apt. kat:1/3 Merkez', sehir: 'Niğde', webSitesi: 'http://www.samistaltravel.com', email: 'samistal@samistaltravel.com', telefon: '3882329151', vergiDairesi: 'NİĞDE', vergiNumarasi: '3100114250', iban: undefined },
    { tip: 'kurum', etiketler: [KAMU], unvan: 'TÜRKİYE SUALTI SPORLARI FEDARASYONU', kisaIsim: 'TSSF', adres: 'FAHRETTİN KERİM GÖKAY CAD D.57 NO 71 ORTAKLAR İŞMERKEZİ KAT 9 KADIKÖY', sehir: 'İstanbul', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'KIZILBEY', vergiNumarasi: '3910242536', iban: undefined },
    { tip: 'kurum', etiketler: [KAMU], unvan: 'SOSYAL GÜVENLİK KURUMU', kisaIsim: 'SGK', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { tip: 'kurum', etiketler: [OTEL], unvan: 'Aslı Veznecioğlu Tur. San. Ve Tic. Ltd. Şti.', kisaIsim: 'RHAPSODY HOTEL KAŞ', adres: 'Andifli Mah. Hukumet Cad. No:45 Kucukcakil Kas', sehir: 'Antalya', webSitesi: 'http://kas.rhapsodyhotels.com', email: 'kas@rhapsodyhotel.com', telefon: '2428361200', vergiDairesi: 'KAŞ', vergiNumarasi: '1080425010', iban: 'TR330006701000000044675085' },
    { tip: 'kurum', etiketler: [OTEL], unvan: 'ÇAPA TURIZM VE YAT İŞLETMELERİ GÜNAY ÇAPA', kisaIsim: 'ÇAPA OTEL', adres: 'ÇUKURBAĞ YARIMADASI NO 8 KAŞ', sehir: 'Antalya', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'KAŞ', vergiNumarasi: '54667041722', iban: undefined },
    { tip: 'kurum', etiketler: [OTEL], unvan: 'Elkon İnşaat Turizm San.ve Tic. ltd. şti.', kisaIsim: 'LUKKA HOTEL KAŞ', adres: 'Cukurbag Yarimadasi, Oteller Bolgesi, Bulent Kalkavan Sk. NO:16 Kas', sehir: 'Antalya', webSitesi: 'http://www.lukkahotel.com/', email: 'booking@lukkahotel.com', telefon: '2428361420', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR520006200107200006299522' },
    { tip: 'kurum', etiketler: [OTEL], unvan: 'BARBAROSSA TURİZM GIDA İNŞ.MOB.TAŞ.TEM.HİZM. VE TİC.LTD.ŞTİ', kisaIsim: 'BARBAROSSA HOTEL&VILLAS', adres: 'Çukurbağ yarımadası, Kaş 07580', sehir: 'Antalya', webSitesi: 'http://www.hotelbarbarossa.com/', email: 'sales@hotelbarbarossa.com', telefon: '2428364071', vergiDairesi: 'KAŞ MM', vergiNumarasi: '430052942', iban: 'TR490006400000162750064021' },
    { tip: 'kurum', etiketler: [OTEL], unvan: 'VURALLAR TURİZM AŞ', kisaIsim: 'PHELLOS HOTEL KAŞ', adres: 'Doğruyol Sok. No:4 07480 Kaş', sehir: 'Antalya', webSitesi: 'http://hotelclubphellos.com', email: 'phelloshotel@yahoo.com.tr', telefon: '2428361953', vergiDairesi: 'BEYOĞLU', vergiNumarasi: '9260018607', iban: 'TR590006701000000072234063' },
    { tip: 'kurum', etiketler: [OTEL], unvan: 'AQUAPRINCESS HOTEL', kisaIsim: 'AQUAPRINCESS HOTEL', adres: 'Hükümet Caddesi No:65 Kaş 07580', sehir: 'Antalya', webSitesi: 'http://www.aquaprincess.com/', email: 'info@aquaprincess.com', telefon: '2428362026', vergiDairesi: 'KAŞ', vergiNumarasi: '11311070644', iban: undefined },
    { tip: 'kurum', etiketler: [OTEL], unvan: 'HOTEL BEGONVİL ASLAN ÇÖL', kisaIsim: 'HOTEL BEGONVİL', adres: 'Küçük Çakıl Mahallesi Koza Sok. No:13 Kaş', sehir: 'Antalya', webSitesi: 'http://www.hotelbegonvil.com', email: 'info@hotelbegonvil.com', telefon: '2428363079', vergiDairesi: 'KAŞ', vergiNumarasi: '2630035692', iban: undefined },
    { tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'OĞUZHAN DURMUŞ', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'oguzhandurmus@msn.com', telefon: '5465391378', vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR020001500158007300447759' },
    { tip: 'sahis', etiketler: [PERSONEL], unvan: undefined, kisaIsim: 'ÖZLEM GÜVENÇ', adres: undefined, sehir: undefined, webSitesi: undefined, email: 'ozlem@dragoman-turkey.com', telefon: '5364165089', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: CKID.CK14, tip: 'kurum', etiketler: [TEDARIKCI], unvan: 'GIANT STRIDE', kisaIsim: 'GÜRSEL TÜZEL', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: '5052996111', vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'SUALTI ARAŞTIRMALARI DERNEĞİ', kisaIsim: 'SAD', adres: 'AKINCILAR SOK 10/1 GMK BULVARI MALTEPE', sehir: 'Ankara', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'MALTEBE', vergiNumarasi: '7810183425', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'ŞAVRAN SİGORTA LTD ŞTİ', kisaIsim: 'SEDAT ŞAVRAN', adres: 'ANDF.MAH ÇUKURBAĞLILAR 2 SOK 5/A KAŞ', sehir: 'Antalya', webSitesi: undefined, email: undefined, telefon: '2428362466', vergiDairesi: 'KAŞ MM', vergiNumarasi: '7530560509', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'SARICAOĞLU MEŞRUBAT VE GIDA MAD.TUR.TİC.LTD.ŞTİ', kisaIsim: 'SARICAOĞLU MEŞRUBAT', adres: 'ANDİFLİ MH ESKİ ANTALYA CD N.218 KAŞ', sehir: 'Antalya', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'KAŞ MM', vergiNumarasi: '7470034107', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: undefined, kisaIsim: 'GAZİEMİR DALIŞ MERKEZİ', adres: 'ATİF BEY MAH BİR SOK NO 1 B GAZİEMİR', sehir: 'İzmir', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'GAZİEMİR', vergiNumarasi: '22103244266', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'BAŞKENT DALIŞ VE İLK YARDIM MERKEZİ', kisaIsim: 'BADİM', adres: 'ESAT CAD 67/5 KÜÇÜKESAT', sehir: 'Ankara', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'CUMHURİYET', vergiNumarasi: '6850049535', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'SOFTAOĞLU TİCARET', kisaIsim: 'HARUN KOCASARI', adres: 'FETHİYE CAD N.8 KAŞ', sehir: 'Antalya', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'KAŞ MM', vergiNumarasi: '13516573708', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'İMEAK DENİZ TİC.ODASI ANTALYA ŞUBESİ', kisaIsim: 'DTO', adres: 'GÜRSU MAH 10.CAD M.ALTUNBAŞ İŞ MERKEZİ NO.19 D.6-7 KONYAALTI', sehir: 'Antalya', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'BEYOĞLU', vergiNumarasi: '4810028802', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'GLOBAL TURİZM SERVİSLERİ TİC.LTD.ŞTİ', kisaIsim: 'Global Turizm', adres: 'HALASKARGAZİ CAD AK APT.NO 135 D.15 KAT.8 ŞİŞLİ', sehir: 'İstanbul', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'ŞİŞLİ', vergiNumarasi: '3960526569', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'KAPTAN YAYINCILIK VE GIDA SAN.DIŞ.TİC.LTD.STİ', kisaIsim: 'DENİZLER KİTAPEVİ', adres: 'İSTİKLAL CAD NO 199/A BEYOĞLU', sehir: 'İstanbul', webSitesi: undefined, email: 'oguz@denizlerkitabevi.com', telefon: '5387042939', vergiDairesi: 'BEYOĞLU', vergiNumarasi: '1910026656', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'DERİNTEK DENİZ VE DOĞA MALZ.LTD ŞTİ', kisaIsim: 'DERİNTEK', adres: 'KORU MAH BOĞAZİÇİ CAD NO 19/A DEMİRCAN APT. İSTİNYE SARIYER', sehir: 'İstanbul', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'SARIYER', vergiNumarasi: '6460205142', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: undefined, kisaIsim: 'KAŞ TURİZM TANITMA DERNEĞİ ', adres: 'MERKEZ MAH HÜKÜMET CAD NO 2 KAŞ', sehir: 'Antalya', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'KAŞ', vergiNumarasi: '5270054157', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'WWF TÜRKİYE DOĞAL HAYATI KORUMA VAKFI', kisaIsim: 'WWF', adres: 'POSTANE CAD NO 19 KAT 5 344200QBAHÇEKAPI', sehir: 'İstanbul', webSitesi: undefined, email: 'yarda@wwf.org.tr', telefon: undefined, vergiDairesi: 'HOCAPAŞA', vergiNumarasi: '3020103609', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'TIP KURUMU DERNEĞİ WHO', kisaIsim: 'HAKAN GÖNENDİK', adres: 'SAĞLIK 2 SOK NO 63/8 KOLEJ SOKAK ÇANKAYA', sehir: 'Ankara', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'ÇANKAYA', vergiNumarasi: '8430258823', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'KD Turizm Seyahat ve Tic. A.Ş', kisaIsim: 'KD TURIZM', adres: 'Teşvikiye Cad. Sadun Apt. No: 19/6 34365, Teşvikiye', sehir: 'İstanbul', webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: 'BEYOĞLU', vergiNumarasi: '4840083551', iban: undefined },
    { tip: 'kurum', etiketler: undefined, unvan: 'Akdeniz Koruma Derneği', kisaIsim: 'ZAFER KIZILKAYA', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: undefined, vergiNumarasi: undefined, iban: 'TR840003200000000010452875' },
    { _id: CKID.CK13, tip: 'kurum', etiketler: [TEDARIKCI], unvan: 'GALATA MARİNE DENİZ MALZEMELERİ TURİZM SAN.VE TİC.LTD.STİ', kisaIsim: 'Galata Marin', adres: 'KEMERALTI CAD.ADA HAN NO 31/B Tophane Beyoğlu', sehir: 'İstanbul', webSitesi: undefined, email: undefined, telefon: '2122512050', vergiDairesi: 'Beyoğlu', vergiNumarasi: '3880441174', iban: undefined },
    { _id: CKID.CK15, tip: 'kurum', etiketler: [TEDARIKCI], unvan: 'TÜRKSPORT SPOR ÜRÜNLERİ SAN VE TİC.LTD.ŞTİ', kisaIsim: 'Decathlon', adres: undefined, sehir: undefined, webSitesi: undefined, email: undefined, telefon: undefined, vergiDairesi: undefined, vergiNumarasi: undefined, iban: undefined },
    { _id: CKID.CK16, tip: 'sahis', etiketler: [TEDARIKCI], unvan: 'ALPTEKİN BALOĞLU', kisaIsim: 'ALPTEKİN BALOĞLU', email: undefined, telefon: '5323139704', sahisBilgileri: { uyruk: 'Türkiye', pasaportVeyaTCNo: '11825387498', diller: [ 'Türkçe' ], cinsiyet: 'erkek', beden: 'XL', ayak: undefined, seakayakSeviyesi: undefined, dalisSertifikasi: 'CMAS', dalisSeviyesi: '2*', dogumTarihi: undefined }},
    { _id: CKID.CK17, tip: 'kurum', etiketler: [TEDARIKCI], kisaIsim: 'MEHMET AVADAN'},
    { _id: CKID.CK18, tip: 'kurum', etiketler: [TEDARIKCI], kisaIsim: 'AZİZ SALTIK'},
    { _id: CKID.CK19, tip: 'kurum', etiketler: [TEDARIKCI], kisaIsim: 'DEAN LIVESLEY'},
    { _id: CKID.CK20, tip: 'kurum', etiketler: [TEDARIKCI], kisaIsim: 'BUKET'},
    { _id: CKID.CK21, tip: 'kurum', etiketler: [TEDARIKCI], kisaIsim: 'INTOVA'},
    { _id: CKID.CK22, tip: 'kurum', etiketler: [TEDARIKCI], kisaIsim: 'IŞIL'},
    { _id: CKID.CK23, tip: 'kurum', etiketler: [TEDARIKCI], unvan: 'KATE CLOW', kisaIsim: 'KARDELEN KARLI'},
    { _id: CKID.CK24, tip: 'kurum', etiketler: [TEDARIKCI], kisaIsim: 'ŞEREF BEY'},
    { _id: CKID.CK25, tip: 'kurum', etiketler: [TEDARIKCI], kisaIsim: 'SUAT'},
  ].forEach(cariKart => {
    CariKartlar.insert(cariKart);
  });

  [
    { cariKart: YKB, tutarX100TL: 903067 },
    { cariKart: YKB_KK_1, tutarX100TL: 548768 },
    { cariKart: YKB_KK_2, tutarX100TL: 623001 },
    { cariKart: PR1, tutarX100TL: 130000 },
    { cariKart: PR2, tutarX100TL: 130000 },
    { cariKart: PR3, tutarX100TL: 130000 },
    { cariKart: PR4, tutarX100TL: 130000 },
    { cariKart: PR5, tutarX100TL: 130000 },
    { cariKart: PR6, tutarX100TL: 130000 },
    { cariKart: PR7, tutarX100TL: 130000 },
    { cariKart: PR8, tutarX100TL: 130000 },
    { cariKart: PR9, tutarX100TL: 130000 },
    { cariKart: PR10, tutarX100TL: 130000 },
    { cariKart: PR11, tutarX100TL: 130000 },
    { cariKart: PR12, tutarX100TL: 130000 },
    { cariKart: PR13, tutarX100TL: 130000 },
    { cariKart: CKID.CK1, tutarX100TL: -420243 },
    { cariKart: CKID.CK2, tutarX100TL: -156000 },
    { cariKart: CKID.CK3, tutarX100TL: -148200 },
    { cariKart: CKID.CK4, tutarX100TL: -133500 },
    { cariKart: CKID.CK5, tutarX100TL: -100000 },
    { cariKart: CKID.CK6, tutarX100TL: -45000 },
    { cariKart: CKID.CK7, tutarX100TL: -35400 },
    { cariKart: CKID.CK8, tutarX100TL: 16000 },
    { cariKart: CKID.CK9, tutarX100TL: 18800 },
    { cariKart: CKID.CK10, tutarX100TL: 20900 },
    { cariKart: CKID.CK11, tutarX100TL: 66400 },
    { cariKart: CKID.CK12, tutarX100TL: 69300 },
  ].forEach(bakiye => {
    Bakiye.Cari.insert(bakiye);
    Bakiye.Cari.Acilis.insert(bakiye);
  });

}
