export const KDVLER = {
  '0': { value: 0, label: '0' },
  '1': { value: 1, label: '1' },
  '8': { value: 8, label: '8' },
  '18': { value: 18, label: '18' },
};

export const URUNLER = {
  MAL: { value: 'mal', label: 'Mal' },
  HIZMET: { value: 'hizmet', label: 'Hizmet' },
};

export const TALEPLER = {
  TAHSILAT: { value: 'tahsilat', label: 'Tahsilat' },
  ODEME: { value: 'odeme', label: 'Ödeme' },
  GELIR: { value: 'gelir', label: 'Gelir' },
  GIDER: { value: 'gider', label: 'Gider' },
};

export const CARI_KARTLAR = {
  KURUM: { value: 'kurum', label: 'Kurum' },
  SAHIS: { value: 'sahis', label: 'Şahıs' },
};

export const KASALAR = {
  NAKIT: { value: 'nakit', label: 'Nakit' },
  KREDI_KARTI: { value: 'krediKarti', label: 'Kredi kartı' },
  BANKA: { value: 'banka', label: 'Banka' },
  KREDILI_MEVDUAT: { value: 'krediliMevduat', label: 'Kredili mevduat' },
  POS: { value: 'pos', label: 'Pos' },
  VADELI_MEVDUAT: { value: 'vadeliMevduat', label: 'Vadeli mevduat' },
  CEK_SENET: { value: 'cekSenet', label: 'Çek senet' },
};

export const KONUMLAR = {
  DEPO: { value: 'depo', label: 'Depo' },
  VITRIN: { value: 'vitrin', label: 'Vitrin' },
};

export const ETIKETLER = {
  CARI_KART: { value: 'cariKart', label: 'Cari kart' },
  MUHASEBE: { value: 'muhasebe', label: 'Muhasebe' },
  URUN: { value: 'urun', label: 'Ürün' },
};

export const SINIFLAR = {
  IS: { value: 'is', label: 'İş' },
  GRUP: { value: 'grup', label: 'Grup' },
  SINIF: { value: 'sinif', label: 'Sınıf' },
};

export const MENSEILER = {
  YERLI: { value: 'yerli', label: 'Yerli' },
  YABANCI: { value: 'yabanci', label: 'Yabancı' },
};

export const KURLAR = {
  TRY: { value: 'TRY', label:'Lira (₺)', name:'Lira', symbol: '₺'},
  USD: { value: 'USD', label:'Dolar ($)', name:'Dolar', symbol: '$'},
  EUR: { value: 'EUR', label:'Avro (€)', name:'Avro', symbol: '€'},
  GBP: { value: 'GBP', label:'Sterlin (£)', name:'Sterlin', symbol: '£'},
};

export const CINSIYETLER = {
  KADIN: { value: 'kadin', label: 'Kadın' },
  ERKEK: { value: 'erkek', label: 'Erkek' },
};

export const SEKAYAK_SEVIYELERI = {
  ILK_KEZ: { value: 'İLK KEZ', label: 'İlk kez' },
  ACEMI: { value: 'ACEMİ', label: 'Acemi' },
  DENEYIMLI: { value: 'DENEYİMLİ', label: 'Deneyimli' },
  ISTEKLI: { value: 'İSTEKLİ', label: 'İstekli' },
  HIRSLI: { value: 'HIRSLI', label: 'Hırslı' },
};

export const BEDENLER = {
  XXS: { value: 'XXS', label: 'XXS' },
  XS: { value: 'XS', label: 'XS' },
  S: { value: 'S', label: 'S' },
  M: { value: 'M', label: 'M' },
  L: { value: 'L', label: 'L' },
  XL: { value: 'XL', label: 'XL' },
  XXL: { value: 'XXL', label: 'XXL' },
  XXXL: { value: 'XXXL', label: 'XXXL' },
  M_L: { value: 'M-L', label: 'M-L' },
  L_XL: { value: 'L-XL', label: 'L-XL' },
  S_M: { value: 'S-M', label: 'S-M' },
};

export const DALIS_SERTIFIKALARI = {
  PADI: { value: 'PADI', label: 'PADI' },
  CMAS: { value: 'CMAS', label: 'CMAS' },
  SSI: { value: 'SSI', label: 'SSI' },
  NAUI: { value: 'NAUI', label: 'NAUI' },
  BSAC: { value: 'BSAC', label: 'BSAC' },
  FFESSM: { value: 'FFESSM', label: 'FFESSM' },
  NIVEAU: { value: 'NIVEAU', label: 'NIVEAU' },
  ANMP: { value: 'ANMP', label: 'ANMP' },
  CEDIP: { value: 'CEDIP', label: 'CEDIP' },
  SDI: { value: 'SDI', label: 'SDI' },
  PROTEC: { value: 'PROTEC', label: 'PROTEC' },
};

export const DALIS_SEVIYELERI = {
  SNRK: { value: 'SNRK', label: 'SNRK' },
  GUIDED_SNRK: { value: 'GUIDED SNRK', label: 'GUIDED SNRK' },
  TRY: { value: 'TRY', label: 'TRY' },
  DSD: { value: 'DSD', label: 'DSD' },
  SD: { value: 'SD', label: 'SD' },
  JOWD: { value: 'JOWD', label: 'JOWD' },
  OWD: { value: 'OWD', label: 'OWD' },
  AOWD: { value: 'AOWD', label: 'AOWD' },
  RD: { value: 'RD', label: 'RD' },
  DM: { value: 'DM', label: 'DM' },
  INST: { value: 'INST', label: 'INST' },
  ONE_STAR: { value: '1*', label: '1*' },
  TWO_START: { value: '2*', label: '2*' },
  THREE_STAR: { value: '3*', label: '3*' },
  DSD_ST: { value: 'DSD-ST', label: 'DSD-ST' },
  SD_ST: { value: 'SD-ST', label: 'SD-ST' },
  OWD_ST: { value: 'OWD-ST', label: 'OWD-ST' },
  AOWD_ST: { value: 'AOWD-ST', label: 'AOWD-ST' },
  RD_ST: { value: 'RD-ST', label: 'RD-ST' },
  DM_ST: { value: 'DM-ST', label: 'DM-ST' },
  ONE_STAR_ST: { value: '1* - ST', label: '1* - ST' },
  TWO_STAR_ST: { value: '2*-ST', label: '2*-ST' },
  THREE_STAR_ST: { value: '3*-ST', label: '3*-ST' },
  ONE_STAR_INST: { value: '1*INST', label: '1*INST' },
  TWO_STAR_INST: { value: '2*INST', label: '2*INST' },
  THREE_STAR_INST: { value: '3*INST', label: '3*INST' },
  SPD: { value: 'SpD', label: 'SpD' },
  MD: { value: 'MD', label: 'MD' },
  DG: { value: 'DG', label: 'DG' },
  OWDCINST: { value: 'OWDCINST', label: 'OWDCINST' },
  ASD: { value: 'ASD', label: 'ASD' },
  MSD: { value: 'MSD', label: 'MSD' },
  INST_: { value: 'INST_', label: 'INST' },
  OCEAN_CLUBD: { value: 'OCEAN/CLUBD', label: 'OCEAN/CLUBD' },
  SPORTD: { value: 'SPORTD', label: 'SPORTD' },
  DL: { value: 'DL', label: 'DL' },
  AD: { value: 'AD', label: 'AD' },
  CLUBINST: { value: 'CLUBINST', label: 'CLUBINST' },
  OWINST: { value: 'OWINST', label: 'OWINST' },
  AINST: { value: 'AINST', label: 'AINST' },
  DEEP_DIVER: { value: 'DEEP DIVER', label: 'DEEP DIVER' },
  NIVEAU1: { value: 'NIVEAU1', label: 'NIVEAU1' },
  NIVEAU2: { value: 'NIVEAU2', label: 'NIVEAU2' },
  NIVEAU3: { value: 'NIVEAU3', label: 'NIVEAU3' },
  MF1: { value: 'MF1', label: 'MF1' },
  EGITIM_KOU: { value: 'EGITIM-KOU', label: 'EGITIM-KOU' },
  JAOWD: { value: 'JAOWD', label: 'JAOWD' },
  PPB_ST: { value: 'PPB-ST', label: 'PPB-ST' },
};

export const SEHIRLER = {
  ADANA: { value: 'Adana', label: 'Adana' },
  ADIYAMAN: { value: 'Adıyaman', label: 'Adıyaman' },
  AFYONKARAHISAR: { value: 'Afyonkarahisar', label: 'Afyonkarahisar' },
  AGRI: { value: 'Ağrı', label: 'Ağrı' },
  AKSARAY: { value: 'Aksaray', label: 'Aksaray' },
  AMASYA: { value: 'Amasya', label: 'Amasya' },
  ANKARA: { value: 'Ankara', label: 'Ankara' },
  ANTALYA: { value: 'Antalya', label: 'Antalya' },
  ARDAHAN: { value: 'Ardahan', label: 'Ardahan' },
  ARTVIN: { value: 'Artvin', label: 'Artvin' },
  AYDIN: { value: 'Aydın', label: 'Aydın' },
  BALIKESIR: { value: 'Balıkesir', label: 'Balıkesir' },
  BARTIN: { value: 'Bartın', label: 'Bartın' },
  BATMAN: { value: 'Batman', label: 'Batman' },
  BAYBURT: { value: 'Bayburt', label: 'Bayburt' },
  BILECIK: { value: 'Bilecik', label: 'Bilecik' },
  BINGOL: { value: 'Bingöl', label: 'Bingöl' },
  BITLIS: { value: 'Bitlis', label: 'Bitlis' },
  BOLU: { value: 'Bolu', label: 'Bolu' },
  BURDUR: { value: 'Burdur', label: 'Burdur' },
  BURSA: { value: 'Bursa', label: 'Bursa' },
  CANAKKALE: { value: 'Çanakkale', label: 'Çanakkale' },
  CANKIRI: { value: 'Çankırı', label: 'Çankırı' },
  CORUM: { value: 'Çorum', label: 'Çorum' },
  DENIZLI: { value: 'Denizli', label: 'Denizli' },
  DIYARBAKIR: { value: 'Diyarbakır', label: 'Diyarbakır' },
  DUZCE: { value: 'Düzce', label: 'Düzce' },
  EDIRNE: { value: 'Edirne', label: 'Edirne' },
  ELAZIG: { value: 'Elazığ', label: 'Elazığ' },
  ERZINCAN: { value: 'Erzincan', label: 'Erzincan' },
  ERZURUM: { value: 'Erzurum', label: 'Erzurum' },
  ESKISEHIR: { value: 'Eskişehir', label: 'Eskişehir' },
  GAZIANTEP: { value: 'Gaziantep', label: 'Gaziantep' },
  GIRESUN: { value: 'Giresun', label: 'Giresun' },
  GUMUSHANE: { value: 'Gümüşhane', label: 'Gümüşhane' },
  HAKKARI: { value: 'Hakkari', label: 'Hakkari' },
  HATAY: { value: 'Hatay', label: 'Hatay' },
  IGDIR: { value: 'Iğdır', label: 'Iğdır' },
  ISPARTA: { value: 'Isparta', label: 'Isparta' },
  ISTANBUL: { value: 'İstanbul', label: 'İstanbul' },
  IZMIR: { value: 'İzmir', label: 'İzmir' },
  KAHRAMANMARAS: { value: 'Kahramanmaraş', label: 'Kahramanmaraş' },
  KARABUK: { value: 'Karabük', label: 'Karabük' },
  KARAMAN: { value: 'Karaman', label: 'Karaman' },
  KARS: { value: 'Kars', label: 'Kars' },
  KASTAMONU: { value: 'Kastamonu', label: 'Kastamonu' },
  KAYSERI: { value: 'Kayseri', label: 'Kayseri' },
  KILIS: { value: 'Kilis', label: 'Kilis' },
  KIRIKKALE: { value: 'Kırıkkale', label: 'Kırıkkale' },
  KIRKLARELI: { value: 'Kırklareli', label: 'Kırklareli' },
  KIRSEHIR: { value: 'Kırşehir', label: 'Kırşehir' },
  KOCAELI: { value: 'Kocaeli', label: 'Kocaeli' },
  KONYA: { value: 'Konya', label: 'Konya' },
  KUTAHYA: { value: 'Kütahya', label: 'Kütahya' },
  MALATYA: { value: 'Malatya', label: 'Malatya' },
  MANISA: { value: 'Manisa', label: 'Manisa' },
  MARDIN: { value: 'Mardin', label: 'Mardin' },
  MERSIN: { value: 'Mersin', label: 'Mersin' },
  MUGLA: { value: 'Muğla', label: 'Muğla' },
  MUS: { value: 'Muş', label: 'Muş' },
  NEVSEHIR: { value: 'Nevşehir', label: 'Nevşehir' },
  NIGDE: { value: 'Niğde', label: 'Niğde' },
  ORDU: { value: 'Ordu', label: 'Ordu' },
  OSMANIYE: { value: 'Osmaniye', label: 'Osmaniye' },
  RIZE: { value: 'Rize', label: 'Rize' },
  SAKARYA: { value: 'Sakarya', label: 'Sakarya' },
  SAMSUN: { value: 'Samsun', label: 'Samsun' },
  SANLIURFA: { value: 'Şanlıurfa', label: 'Şanlıurfa' },
  SIIRT: { value: 'Siirt', label: 'Siirt' },
  SINOP: { value: 'Sinop', label: 'Sinop' },
  SIVAS: { value: 'Sivas', label: 'Sivas' },
  SIRNAK: { value: 'Şırnak', label: 'Şırnak' },
  TEKIRDAG: { value: 'Tekirdağ', label: 'Tekirdağ' },
  TOKAT: { value: 'Tokat', label: 'Tokat' },
  TRABZON: { value: 'Trabzon', label: 'Trabzon' },
  TUNCELI: { value: 'Tunceli', label: 'Tunceli' },
  USAK: { value: 'Uşak', label: 'Uşak' },
  VAN: { value: 'Van', label: 'Van' },
  YALOVA: { value: 'Yalova', label: 'Yalova' },
  YOZGAT: { value: 'Yozgat', label: 'Yozgat' },
  ZONGULDAK: { value: 'Zonguldak', label: 'Zonguldak' },
};

export const DILLER = {
  ALMANCA: { value: 'Almanca', label: 'Almanca' },
  FRANSIZCA: { value: 'Fransızca', label: 'Fransızca' },
  INGILIZCE: { value: 'İngilizce', label: 'İngilizce' },
  RUSCA: { value: 'Rusça', label: 'Rusça' },
  TURKCE: { value: 'Türkçe', label: 'Türkçe' },
  DIGER: { value: 'Diğer', label: 'Diğer' },
};

export const ULKELER = {
  US: { value: 'ABD', label: 'ABD' },
  UM: { value: 'ABD Uzak Adaları', label: 'ABD Uzak Adaları' },
  VI: { value: 'ABD Virjin Adaları', label: 'ABD Virjin Adaları' },
  AF: { value: 'Afganistan', label: 'Afganistan' },
  AX: { value: 'Åland Adaları', label: 'Åland Adaları' },
  DE: { value: 'Almanya', label: 'Almanya' },
  AS: { value: 'Amerikan Samoası', label: 'Amerikan Samoası' },
  AD: { value: 'Andorra', label: 'Andorra' },
  AO: { value: 'Angola', label: 'Angola' },
  AI: { value: 'Anguilla', label: 'Anguilla' },
  AQ: { value: 'Antarktika', label: 'Antarktika' },
  AG: { value: 'Antigua ve Barbuda', label: 'Antigua ve Barbuda' },
  AR: { value: 'Arjantin', label: 'Arjantin' },
  AL: { value: 'Arnavutluk', label: 'Arnavutluk' },
  AW: { value: 'Aruba', label: 'Aruba' },
  AC: { value: 'Ascension Adası', label: 'Ascension Adası' },
  AU: { value: 'Avustralya', label: 'Avustralya' },
  AT: { value: 'Avusturya', label: 'Avusturya' },
  AZ: { value: 'Azerbaycan', label: 'Azerbaycan' },
  BS: { value: 'Bahamalar', label: 'Bahamalar' },
  BH: { value: 'Bahreyn', label: 'Bahreyn' },
  BD: { value: 'Bangladeş', label: 'Bangladeş' },
  BB: { value: 'Barbados', label: 'Barbados' },
  EH: { value: 'Batı Sahara', label: 'Batı Sahara' },
  BE: { value: 'Belçika', label: 'Belçika' },
  BZ: { value: 'Belize', label: 'Belize' },
  BJ: { value: 'Benin', label: 'Benin' },
  BM: { value: 'Bermuda', label: 'Bermuda' },
  BY: { value: 'Beyaz Rusya', label: 'Beyaz Rusya' },
  AE: { value: 'Birleşik Arap Emirlikleri', label: 'Birleşik Arap Emirlikleri' },
  GB: { value: 'Birleşik Krallık', label: 'Birleşik Krallık' },
  BO: { value: 'Bolivya', label: 'Bolivya' },
  BA: { value: 'Bosna Hersek', label: 'Bosna Hersek' },
  BW: { value: 'Botsvana', label: 'Botsvana' },
  BR: { value: 'Brezilya', label: 'Brezilya' },
  IO: { value: 'Britanya Hint Okyanusu Toprakları', label: 'Britanya Hint Okyanusu Toprakları' },
  VG: { value: 'Britanya Virjin Adaları', label: 'Britanya Virjin Adaları' },
  BN: { value: 'Brunei', label: 'Brunei' },
  BG: { value: 'Bulgaristan', label: 'Bulgaristan' },
  BF: { value: 'Burkina Faso', label: 'Burkina Faso' },
  BI: { value: 'Burundi', label: 'Burundi' },
  BT: { value: 'Butan', label: 'Butan' },
  TD: { value: 'Çad', label: 'Çad' },
  CV: { value: 'Cape Verde', label: 'Cape Verde' },
  KY: { value: 'Cayman Adaları', label: 'Cayman Adaları' },
  GI: { value: 'Cebelitarık', label: 'Cebelitarık' },
  CZ: { value: 'Çek Cumhuriyeti', label: 'Çek Cumhuriyeti' },
  DZ: { value: 'Cezayir', label: 'Cezayir' },
  CX: { value: 'Christmas Adası', label: 'Christmas Adası' },
  DJ: { value: 'Cibuti', label: 'Cibuti' },
  CN: { value: 'Çin', label: 'Çin' },
  HK: { value: 'Çin Hong Kong ÖYB', label: 'Çin Hong Kong ÖYB' },
  MO: { value: 'Çin Makao ÖYB', label: 'Çin Makao ÖYB' },
  CC: { value: 'Cocos (Keeling) Adaları', label: 'Cocos (Keeling) Adaları' },
  CK: { value: 'Cook Adaları', label: 'Cook Adaları' },
  CW: { value: 'Curaçao', label: 'Curaçao' },
  DK: { value: 'Danimarka', label: 'Danimarka' },
  DG: { value: 'Diego Garcia', label: 'Diego Garcia' },
  DO: { value: 'Dominik Cumhuriyeti', label: 'Dominik Cumhuriyeti' },
  DM: { value: 'Dominika', label: 'Dominika' },
  EC: { value: 'Ekvador', label: 'Ekvador' },
  GQ: { value: 'Ekvator Ginesi', label: 'Ekvator Ginesi' },
  SV: { value: 'El Salvador', label: 'El Salvador' },
  ID: { value: 'Endonezya', label: 'Endonezya' },
  ER: { value: 'Eritre', label: 'Eritre' },
  AM: { value: 'Ermenistan', label: 'Ermenistan' },
  EE: { value: 'Estonya', label: 'Estonya' },
  ET: { value: 'Etiyopya', label: 'Etiyopya' },
  FK: { value: 'Falkland Adaları', label: 'Falkland Adaları' },
  FO: { value: 'Faroe Adaları', label: 'Faroe Adaları' },
  MA: { value: 'Fas', label: 'Fas' },
  FJ: { value: 'Fiji', label: 'Fiji' },
  CI: { value: 'Fildişi Sahili', label: 'Fildişi Sahili' },
  PH: { value: 'Filipinler', label: 'Filipinler' },
  PS: { value: 'Filistin Bölgeleri', label: 'Filistin Bölgeleri' },
  FI: { value: 'Finlandiya', label: 'Finlandiya' },
  FR: { value: 'Fransa', label: 'Fransa' },
  TF: { value: 'Fransız Güney Toprakları', label: 'Fransız Güney Toprakları' },
  GF: { value: 'Fransız Guyanası', label: 'Fransız Guyanası' },
  PF: { value: 'Fransız Polinezyası', label: 'Fransız Polinezyası' },
  GA: { value: 'Gabon', label: 'Gabon' },
  GM: { value: 'Gambiya', label: 'Gambiya' },
  GH: { value: 'Gana', label: 'Gana' },
  GN: { value: 'Gine', label: 'Gine' },
  GW: { value: 'Gine-Bissau', label: 'Gine-Bissau' },
  GD: { value: 'Grenada', label: 'Grenada' },
  GL: { value: 'Grönland', label: 'Grönland' },
  GP: { value: 'Guadalupe', label: 'Guadalupe' },
  GU: { value: 'Guam', label: 'Guam' },
  GT: { value: 'Guatemala', label: 'Guatemala' },
  GG: { value: 'Guernsey', label: 'Guernsey' },
  ZA: { value: 'Güney Afrika', label: 'Güney Afrika' },
  GS: { value: 'Güney Georgia ve Güney Sandwich Adaları', label: 'Güney Georgia ve Güney Sandwich Adaları' },
  CY: { value: 'Güney Kıbrıs Rum Kesimi', label: 'Güney Kıbrıs Rum Kesimi' },
  KR: { value: 'Güney Kore', label: 'Güney Kore' },
  SS: { value: 'Güney Sudan', label: 'Güney Sudan' },
  GE: { value: 'Gürcistan', label: 'Gürcistan' },
  GY: { value: 'Guyana', label: 'Guyana' },
  HT: { value: 'Haiti', label: 'Haiti' },
  IN: { value: 'Hindistan', label: 'Hindistan' },
  HR: { value: 'Hırvatistan', label: 'Hırvatistan' },
  NL: { value: 'Hollanda', label: 'Hollanda' },
  HN: { value: 'Honduras', label: 'Honduras' },
  IQ: { value: 'Irak', label: 'Irak' },
  IR: { value: 'İran', label: 'İran' },
  IE: { value: 'İrlanda', label: 'İrlanda' },
  ES: { value: 'İspanya', label: 'İspanya' },
  IL: { value: 'İsrail', label: 'İsrail' },
  SE: { value: 'İsveç', label: 'İsveç' },
  CH: { value: 'İsviçre', label: 'İsviçre' },
  IT: { value: 'İtalya', label: 'İtalya' },
  IS: { value: 'İzlanda', label: 'İzlanda' },
  JM: { value: 'Jamaika', label: 'Jamaika' },
  JP: { value: 'Japonya', label: 'Japonya' },
  JE: { value: 'Jersey', label: 'Jersey' },
  KH: { value: 'Kamboçya', label: 'Kamboçya' },
  CM: { value: 'Kamerun', label: 'Kamerun' },
  CA: { value: 'Kanada', label: 'Kanada' },
  IC: { value: 'Kanarya Adaları', label: 'Kanarya Adaları' },
  ME: { value: 'Karadağ', label: 'Karadağ' },
  BQ: { value: 'Karayip Hollanda', label: 'Karayip Hollanda' },
  QA: { value: 'Katar', label: 'Katar' },
  KZ: { value: 'Kazakistan', label: 'Kazakistan' },
  KE: { value: 'Kenya', label: 'Kenya' },
  KI: { value: 'Kiribati', label: 'Kiribati' },
  KG: { value: 'Kırgızistan', label: 'Kırgızistan' },
  CO: { value: 'Kolombiya', label: 'Kolombiya' },
  KM: { value: 'Komorlar', label: 'Komorlar' },
  CG: { value: 'Kongo - Brazavil', label: 'Kongo - Brazavil' },
  CD: { value: 'Kongo - Kinşasa', label: 'Kongo - Kinşasa' },
  XK: { value: 'Kosova', label: 'Kosova' },
  CR: { value: 'Kosta Rika', label: 'Kosta Rika' },
  CU: { value: 'Küba', label: 'Küba' },
  KW: { value: 'Kuveyt', label: 'Kuveyt' },
  KP: { value: 'Kuzey Kore', label: 'Kuzey Kore' },
  MP: { value: 'Kuzey Mariana Adaları', label: 'Kuzey Mariana Adaları' },
  LA: { value: 'Laos', label: 'Laos' },
  LS: { value: 'Lesoto', label: 'Lesoto' },
  LV: { value: 'Letonya', label: 'Letonya' },
  LR: { value: 'Liberya', label: 'Liberya' },
  LY: { value: 'Libya', label: 'Libya' },
  LI: { value: 'Liechtenstein', label: 'Liechtenstein' },
  LT: { value: 'Litvanya', label: 'Litvanya' },
  LB: { value: 'Lübnan', label: 'Lübnan' },
  LU: { value: 'Lüksemburg', label: 'Lüksemburg' },
  HU: { value: 'Macaristan', label: 'Macaristan' },
  MG: { value: 'Madagaskar', label: 'Madagaskar' },
  MK: { value: 'Makedonya', label: 'Makedonya' },
  MW: { value: 'Malavi', label: 'Malavi' },
  MV: { value: 'Maldivler', label: 'Maldivler' },
  MY: { value: 'Malezya', label: 'Malezya' },
  ML: { value: 'Mali', label: 'Mali' },
  MT: { value: 'Malta', label: 'Malta' },
  IM: { value: 'Man Adası', label: 'Man Adası' },
  MH: { value: 'Marshall Adaları', label: 'Marshall Adaları' },
  MQ: { value: 'Martinik', label: 'Martinik' },
  MU: { value: 'Mauritius', label: 'Mauritius' },
  YT: { value: 'Mayotte', label: 'Mayotte' },
  MX: { value: 'Meksika', label: 'Meksika' },
  FM: { value: 'Mikronezya', label: 'Mikronezya' },
  EG: { value: 'Mısır', label: 'Mısır' },
  MN: { value: 'Moğolistan', label: 'Moğolistan' },
  MD: { value: 'Moldova', label: 'Moldova' },
  MC: { value: 'Monako', label: 'Monako' },
  MS: { value: 'Montserrat', label: 'Montserrat' },
  MR: { value: 'Moritanya', label: 'Moritanya' },
  MZ: { value: 'Mozambik', label: 'Mozambik' },
  MM: { value: 'Myanmar (Burma)', label: 'Myanmar (Burma)' },
  NA: { value: 'Namibya', label: 'Namibya' },
  NR: { value: 'Nauru', label: 'Nauru' },
  NP: { value: 'Nepal', label: 'Nepal' },
  NE: { value: 'Nijer', label: 'Nijer' },
  NG: { value: 'Nijerya', label: 'Nijerya' },
  NI: { value: 'Nikaragua', label: 'Nikaragua' },
  NU: { value: 'Niue', label: 'Niue' },
  NF: { value: 'Norfolk Adası', label: 'Norfolk Adası' },
  NO: { value: 'Norveç', label: 'Norveç' },
  CF: { value: 'Orta Afrika Cumhuriyeti', label: 'Orta Afrika Cumhuriyeti' },
  UZ: { value: 'Özbekistan', label: 'Özbekistan' },
  PK: { value: 'Pakistan', label: 'Pakistan' },
  PW: { value: 'Palau', label: 'Palau' },
  PA: { value: 'Panama', label: 'Panama' },
  PG: { value: 'Papua Yeni Gine', label: 'Papua Yeni Gine' },
  PY: { value: 'Paraguay', label: 'Paraguay' },
  PE: { value: 'Peru', label: 'Peru' },
  PN: { value: 'Pitcairn Adaları', label: 'Pitcairn Adaları' },
  PL: { value: 'Polonya', label: 'Polonya' },
  PT: { value: 'Portekiz', label: 'Portekiz' },
  PR: { value: 'Porto Riko', label: 'Porto Riko' },
  RE: { value: 'Réunion', label: 'Réunion' },
  RO: { value: 'Romanya', label: 'Romanya' },
  RW: { value: 'Ruanda', label: 'Ruanda' },
  RU: { value: 'Rusya', label: 'Rusya' },
  BL: { value: 'Saint Barthelemy', label: 'Saint Barthelemy' },
  SH: { value: 'Saint Helena', label: 'Saint Helena' },
  KN: { value: 'Saint Kitts ve Nevis', label: 'Saint Kitts ve Nevis' },
  LC: { value: 'Saint Lucia', label: 'Saint Lucia' },
  MF: { value: 'Saint Martin', label: 'Saint Martin' },
  PM: { value: 'Saint Pierre ve Miquelon', label: 'Saint Pierre ve Miquelon' },
  VC: { value: 'Saint Vincent ve Grenadinler', label: 'Saint Vincent ve Grenadinler' },
  WS: { value: 'Samoa', label: 'Samoa' },
  SM: { value: 'San Marino', label: 'San Marino' },
  ST: { value: 'São Tomé ve Príncipe', label: 'São Tomé ve Príncipe' },
  SN: { value: 'Senegal', label: 'Senegal' },
  EA: { value: 'Septe ve Melilla', label: 'Septe ve Melilla' },
  SC: { value: 'Seyşeller', label: 'Seyşeller' },
  SL: { value: 'Sierra Leone', label: 'Sierra Leone' },
  CL: { value: 'Şili', label: 'Şili' },
  SG: { value: 'Singapur', label: 'Singapur' },
  SX: { value: 'Sint Maarten', label: 'Sint Maarten' },
  RS: { value: 'Sırbistan', label: 'Sırbistan' },
  SK: { value: 'Slovakya', label: 'Slovakya' },
  SI: { value: 'Slovenya', label: 'Slovenya' },
  SB: { value: 'Solomon Adaları', label: 'Solomon Adaları' },
  SO: { value: 'Somali', label: 'Somali' },
  LK: { value: 'Sri Lanka', label: 'Sri Lanka' },
  SD: { value: 'Sudan', label: 'Sudan' },
  SR: { value: 'Surinam', label: 'Surinam' },
  SY: { value: 'Suriye', label: 'Suriye' },
  SA: { value: 'Suudi Arabistan', label: 'Suudi Arabistan' },
  SJ: { value: 'Svalbard ve Jan Mayen Adaları', label: 'Svalbard ve Jan Mayen Adaları' },
  SZ: { value: 'Svaziland', label: 'Svaziland' },
  TJ: { value: 'Tacikistan', label: 'Tacikistan' },
  TZ: { value: 'Tanzanya', label: 'Tanzanya' },
  TH: { value: 'Tayland', label: 'Tayland' },
  TW: { value: 'Tayvan', label: 'Tayvan' },
  TL: { value: 'Timor-Leste', label: 'Timor-Leste' },
  TG: { value: 'Togo', label: 'Togo' },
  TK: { value: 'Tokelau', label: 'Tokelau' },
  TO: { value: 'Tonga', label: 'Tonga' },
  TT: { value: 'Trinidad ve Tobago', label: 'Trinidad ve Tobago' },
  TA: { value: 'Tristan da Cunha', label: 'Tristan da Cunha' },
  TN: { value: 'Tunus', label: 'Tunus' },
  TR: { value: 'Türkiye', label: 'Türkiye' },
  TM: { value: 'Türkmenistan', label: 'Türkmenistan' },
  TC: { value: 'Turks ve Caicos Adaları', label: 'Turks ve Caicos Adaları' },
  TV: { value: 'Tuvalu', label: 'Tuvalu' },
  UG: { value: 'Uganda', label: 'Uganda' },
  UA: { value: 'Ukrayna', label: 'Ukrayna' },
  OM: { value: 'Umman', label: 'Umman' },
  JO: { value: 'Ürdün', label: 'Ürdün' },
  UY: { value: 'Uruguay', label: 'Uruguay' },
  VU: { value: 'Vanuatu', label: 'Vanuatu' },
  VA: { value: 'Vatikan', label: 'Vatikan' },
  VE: { value: 'Venezuela', label: 'Venezuela' },
  VN: { value: 'Vietnam', label: 'Vietnam' },
  WF: { value: 'Wallis ve Futuna Adaları', label: 'Wallis ve Futuna Adaları' },
  YE: { value: 'Yemen', label: 'Yemen' },
  NC: { value: 'Yeni Kaledonya', label: 'Yeni Kaledonya' },
  NZ: { value: 'Yeni Zelanda', label: 'Yeni Zelanda' },
  GR: { value: 'Yunanistan', label: 'Yunanistan' },
  ZM: { value: 'Zambiya', label: 'Zambiya' },
  ZW: { value: 'Zimbabve', label: 'Zimbabve' },
};
